# Generated by Django 4.2 on 2024-08-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('author', models.CharField(max_length=200)),
                ('images_book', models.ImageField(blank=True, null=True, upload_to='books/%Y/%m/%d')),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=700)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['name'], name='book_genre_name_ea47b5_idx'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(related_name='genre_books', to='book.genre'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='book_book_title_b5b75a_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author'], name='book_book_author_33a3f1_idx'),
        ),
    ]
