# Generated by Django 4.2 on 2024-08-19 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_language_genre_slug_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
    ]
