# Generated by Django 4.2 on 2024-08-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='images_book',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
