# Generated by Django 4.2 on 2024-08-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_genre_options_alter_genre_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publishing_house',
            field=models.CharField(default='АСТ', max_length=50),
            preserve_default=False,
        ),
    ]
