# Generated by Django 4.2 on 2024-08-27 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_book_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created']},
        ),
    ]
