# Generated by Django 4.2 on 2024-08-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingstatus',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
